{"uuid":"5c5fea27-95c1-4292-a234-ee6e70867d62","historyId":"659b290311c7f34d3f8232c0465e9a5f","fullName":"com.realestatecrm.tests.ValidLoginTest.testValidLogin","labels":[{"name":"package","value":"com.realestatecrm.tests.ValidLoginTest"},{"name":"testClass","value":"com.realestatecrm.tests.ValidLoginTest"},{"name":"testMethod","value":"testValidLogin"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"LoginAutomation"},{"name":"subSuite","value":"com.realestatecrm.tests.ValidLoginTest"},{"name":"host","value":"DESKTOP-6JH7O92"},{"name":"thread","value":"6520@DESKTOP-6JH7O92.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Valid Login Scenario"},{"name":"severity","value":"blocker"}],"links":[],"name":"testValidLogin","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Login was successful expected [true] but found [false]","trace":"java.lang.AssertionError: Login was successful expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat com.realestatecrm.tests.ValidLoginTest.testValidLogin(ValidLoginTest.java:28)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Test Description: Verify successful login with valid credentials","steps":[],"attachments":[],"parameters":[],"start":1747219056552,"stop":1747219059728}